## Numpy array and basics
Learn about numpy with chai and code

import numpy as np

In [1]:
import numpy as np

### creating array from list

In [3]:
arr_1d=np.array([1,2,3,4,5])
print(arr_1d)

arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


###  list vs numpy array

In [5]:
py_list=[1,2,3]
print(py_list)

[1, 2, 3]
